baseurl = "http://anthony-raborn.netlify.com/"
canonifyURLs = true
languageCode = "en-us"
title = "Unstandard Deviations"
theme = "hugo-xmin"
googleAnalytics = "UA-117105788-1"
disqusShortname = "unstandarddeviations-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Main Page"
    url = ""
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/AnthonyRaborn"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/AnthonyRaborn"
    weight = 4
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/anthony-raborn-317a01107/"
    weight = 5

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

